create_rhcos_image: false
hostname: manila-cloud
clouddomain: ci.vexxhost.ca
control_plane_ip: 38.102.83.64 # floating IP used for OpenStack endpoints

ssl_enabled: true
manila_enabled: true
ceph_devices:
  - /dev/sdc
authorized_keys:
  - https://github.com/mandre.keys
