clouddomain: ci.vexxhost.ca
manila_enabled: true
ceph_devices:
  - /dev/sdb
ephemeral_storage_devices:
  - /dev/sdc
  - /dev/sdd
swiftoperator_enabled: false
rhsm_enabled: true
standalone_extra_config:
  octavia::wsgi::apache:workers: 4
  tripleo::firewall::firewall_rules:
    '168 allow squid':
      dport: 3128
      proto: tcp
      action: accept
sriov_interface: enp129s0f1
sriov_nova_pci_passthrough:
  - devname: "enp129s0f1"
    physical_network: "hostonly-sriov"
sriov_nic_numvfs: 63
dpdk_interface: enp65s0f0
# ======================================================================
# Core and Socket Information (as reported by '/sys/devices/system/cpu')
# ======================================================================
# 
# cores =  [0, 1, 2, 4, 5, 6, 8, 9, 10, 12, 13, 14, 16, 17, 18, 20, 21, 22, 24, 25, 26, 28, 29, 30]
# sockets =  [0, 1]
# 
#         Socket 0        Socket 1       
#         --------        --------       
# Core 0  [0, 48]         [24, 72]       
# Core 1  [1, 49]         [25, 73]       
# Core 2  [2, 50]         [26, 74]       
# Core 4  [3, 51]         [27, 75]       
# Core 5  [4, 52]         [28, 76]       
# Core 6  [5, 53]         [29, 77]       
# Core 8  [6, 54]         [30, 78]       
# Core 9  [7, 55]         [31, 79]       
# Core 10 [8, 56]         [32, 80]       
# Core 12 [9, 57]         [33, 81]       
# Core 13 [10, 58]        [34, 82]       
# Core 14 [11, 59]        [35, 83]       
# Core 16 [12, 60]        [36, 84]       
# Core 17 [13, 61]        [37, 85]       
# Core 18 [14, 62]        [38, 86]       
# Core 20 [15, 63]        [39, 87]       
# Core 21 [16, 64]        [40, 88]       
# Core 22 [17, 65]        [41, 89]       
# Core 24 [18, 66]        [42, 90]       
# Core 25 [19, 67]        [43, 91]       
# Core 26 [20, 68]        [44, 92]       
# Core 28 [21, 69]        [45, 93]       
# Core 29 [22, 70]        [46, 94]       
# Core 30 [23, 71]        [47, 95]
#
kernel_args: "default_hugepagesz=1GB hugepagesz=1G hugepages=469 iommu=pt amd_iommu=on isolcpus=10-23,58-71,34-47,82-95"
tuned_isolated_cores: 10-23,58-71,34-47,82-95
extra_heat_params:
  # We plan to have a maximum of 2 OCP clusters deployed at the same time,
  # which represents 6 OCP workers, where each consumes 8 VCPUs.
  # 6 * 8 = 48
  # We have 2 NUMA nodes where each sibling has 2 threads so:
  # 48 / 4 = 12 cores reserved
  # 48 / 2 = 24 threads reserved and configured here:
  NovaComputeCpuDedicatedSet: "12-23,60-71,36-47,84-95"
  # Recommanded value & the default already in OSP
  NovaReservedHostMemory: 4096
  NovaComputeCpuSharedSet: "0-9,48-57,24-33,72-81"
  OvsDpdkSocketMemory: "2048,2048"
  OvsPmdCoreList: 10-11,58-59,34-35,82-83
post_install: |
  sudo dnf install -y wget
  export OS_CLOUD=standalone
  for i in m1.xlarge m1.large.nodisk m1.xlarge.nodisk m1.large m1.medium m1.tiny m1.small; do openstack flavor set --no-property --property hw:mem_page_size=large $i; done
  openstack flavor delete m1.xlarge.nfv
  openstack flavor create --ram 16384 --disk 40 --vcpu 8 --public m1.xlarge.nfv
  openstack flavor set --property hw:cpu_policy=dedicated --property hw:mem_page_size=large m1.xlarge.nfv
  openstack image show centos8-stream || wget https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20210210.0.x86_64.qcow2 && openstack image create --public --disk-format qcow2 --file CentOS-Stream-GenericCloud-8-20210210.0.x86_64.qcow2 centos8-stream && rm -f CentOS-Stream-GenericCloud-8-20210210.0.x86_64.qcow2
  openstack quota set --cores 120 --fixed-ips -1 --injected-file-size -1 --injected-files -1 --instances -1 --key-pairs -1 --properties -1 --ram 450000 --gigabytes 4000 --server-groups -1 --server-group-members -1 --backups -1 --backup-gigabytes -1 --per-volume-gigabytes -1 --snapshots -1 --volumes -1 --floating-ips 80 --secgroup-rules -1 --secgroups -1 --networks -1 --subnets -1 --ports -1 --routers -1 --rbac-policies -1 --subnetpools -1 openshift
  sudo podman create --net=host --name=squid --volume /home/stack/squid/squid.conf:/etc/squid/squid.conf:z --volume /home/stack/squid/htpasswd:/etc/squid/htpasswd:z quay.io/emilien/squid:latest
  sudo podman generate systemd --name squid | sudo tee -a /etc/systemd/system/container-squid.service
  sudo systemctl enable --now container-squid
