clouddomain: ci.vexxhost.ca
manila_enabled: true
ceph_devices:
  # 894.3 GiB total for Cinder and Manila
  - /dev/disk/by-path/pci-0000:46:00.0-ata-3 # 894.3 GiB
ephemeral_storage_devices:
  # 1.1 TiB total for Nova instances
  - /dev/disk/by-path/pci-0000:46:00.0-ata-2 # 223.6 GiB
  - /dev/disk/by-path/pci-0000:46:00.0-ata-4 # 894.3 GiB
# https://bugzilla.redhat.com/show_bug.cgi?id=2235819
# https://support.vexxhost.com/hc/en-us/requests/364632
# https://support.vexxhost.com/hc/en-us/requests/364694
# This is because the system see the disks as removable and Ceph
# will refuse to use them.
ceph_devices_to_lvm: true
swiftoperator_enabled: false
rhsm_enabled: true
standalone_extra_config:
  octavia::wsgi::apache::workers: 4
neutron_bridge_mappings: hostonly:br-hostonly,mellanox-dpdk:br-mlx-dpdk
neutron_flat_networks: hostonly,hostonly-sriov,mellanox-sriov,mellanox-dpdk
neutron_physical_dev_mappings: hostonly-sriov:enp193s0f1,mellanox-sriov:enp161s0f1np1
sriov_interface: enp129s0f1np1
sriov_nova_pci_passthrough:
  - devname: "enp193s0f1"
    physical_network: "hostonly-sriov"
  - devname: "enp161s0f1np1"
    physical_network: "mellanox-sriov"
sriov_nic_numvfs: 8
dpdk_interface: enp193s0f0
kernel_args: "default_hugepagesz=1GB hugepagesz=1G hugepages=420 iommu=pt amd_iommu=on isolcpus=10-23,58-71,34-47,82-95"
tuned_isolated_cores: 10-23,58-71,34-47,82-95
extra_heat_params:
  NovaComputeCpuDedicatedSet: "10-23,58-71,34-47,82-95"
  NovaReservedHostMemory: 4096
  NovaComputeCpuSharedSet: "0-9,48-57,24-33,72-81"
  OvsDpdkSocketMemory: "2048,2048"
  OvsPmdCoreList: "10,34"
  ExtraFirewallRules:
    '168 allow squid':
      dport: 3128
      proto: tcp
      action: insert
  # Turn off debug
  Debug: false
  # But restore debug for the services we care about
  CinderDebug: true
  GlanceDebug: true
  KeystoneDebug: true
  NeutronDebug: true
  NovaDebug: true
  ManilaDebug: true
  OctaviaDebug: true
network_config:
  - type: interface
    name: dummy0
    use_dhcp: false
    nm_controlled: true
  - type: ovs_user_bridge
    name: br-hostonly
    use_dhcp: false
    ovs_extra:
    - br-set-external-id br-hostonly bridge-id br-hostonly
    addresses:
    - ip_netmask: 192.168.25.1/32
    routes:
    - destination: 192.168.25.0/24
      nexthop: 192.168.25.1
    members:
    - type: ovs_dpdk_port
      name: dpdk
      rx_queue: 1
      members:
      - type: interface
        name: enp193s0f0
  - type: ovs_user_bridge
    name: br-mlx-dpdk
    use_dhcp: false
    ovs_extra:
    - br-set-external-id br-mlx-dpdk bridge-id br-mlx-dpdk
    addresses:
    - ip_netmask: 192.168.28.1/32
    routes:
    - destination: 192.168.28.0/24
      nexthop: 192.168.28.1
    members:
    - type: ovs_dpdk_port
      name: dpdk
      rx_queue: 1
      driver: mlx5_core
      members:
      - type: interface
        name: enp161s0f0np0
  - type: sriov_pf
    name: enp193s0f1
    use_dhcp: false
    numvfs: 8
    defroute: false
    nm_controlled: true
    hotplug: true
    promisc: false
    addresses:
    - ip_netmask: 192.168.26.1/24
  - type: sriov_pf
    name: enp161s0f1np1
    use_dhcp: false
    numvfs: 8
    defroute: false
    nm_controlled: true
    hotplug: true
    promisc: false
    addresses:
    - ip_netmask: 192.168.27.1/24
post_install: |
  sudo dnf install -y wget
  export OS_CLOUD=standalone
  openstack image show centos9-stream || wget https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2 && openstack image create --public --disk-format qcow2 --file CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2 centos9-stream && rm -f CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
  openstack network set --name intel-sriov hostonly-sriov
  openstack subnet set --name intel-sriov-subnet hostonly-sriov-subnet
  openstack network set --name intel-dpdk hostonly
  openstack subnet set --name intel-dpdk-subnet hostonly-subnet
  openstack network create --project openshift --share --external --provider-physical-network mellanox-sriov --provider-network-type flat mellanox-sriov
  openstack subnet create --project openshift mellanox-sriov-subnet --subnet-range 192.168.27.0/24 --no-dhcp --gateway 192.168.27.1 --allocation-pool "start=192.168.27.2,end=192.168.27.254" --network mellanox-sriov
  openstack network create --project openshift --share --external --provider-physical-network mellanox-dpdk --provider-network-type flat mellanox-dpdk
  openstack subnet create --project openshift mellanox-dpdk-subnet --subnet-range 192.168.28.0/24 --dhcp --gateway 192.168.28.1 --allocation-pool "start=192.168.28.2,end=192.168.28.254" --network mellanox-dpdk
  for i in m1.xlarge m1.large.nodisk m1.xlarge.nodisk m1.large m1.medium m1.tiny m1.small; do openstack flavor set --no-property --property hw:mem_page_size=large $i; done
  openstack flavor delete m1.xlarge.nfv
  openstack flavor create --ram 16384 --disk 40 --vcpu 8 --public m1.xlarge.nfv
  openstack flavor set --property hw:cpu_policy=dedicated --property hw:mem_page_size=large --property hw:pci_numa_affinity_policy=preferred m1.xlarge.nfv
  openstack flavor create --ram 16384 --disk 40 --vcpu 4 --public m1.xlarge.2
  openstack image show centos9-stream || wget https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2 && openstack image create --public --disk-format qcow2 --file CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2 centos9-stream && rm -f CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2
  openstack quota set --cores 120 --fixed-ips -1 --injected-file-size -1 --injected-files -1 --instances -1 --key-pairs -1 --properties -1 --ram 450000 --gigabytes 4000 --server-groups -1 --server-group-members -1 --backups -1 --backup-gigabytes -1 --per-volume-gigabytes -1 --snapshots -1 --volumes -1 --floating-ips 80 --secgroup-rules -1 --secgroups -1 --networks -1 --subnets -1 --ports -1 --routers -1 --rbac-policies -1 --subnetpools -1 openshift
  sudo podman create --net=host --name=squid --volume /home/stack/squid/squid.conf:/etc/squid/squid.conf:z --volume /home/stack/squid/htpasswd:/etc/squid/htpasswd:z quay.io/emilien/squid:latest
  sudo podman generate systemd --name squid | sudo tee -a /etc/systemd/system/container-squid.service
  sudo systemctl enable --now container-squid
